server:
  port: 8060   # Port sur lequel l'application va démarrer

spring:
  application:
    name: Recrutement
  datasource:
    url: jdbc:mysql://localhost:3306/Recrutement?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root  # Nom d'utilisateur de la base de données
    password:       # Mot de passe de la base de données (laissez vide si aucun mot de passe)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Met à jour le schéma de la base de données automatiquement
    show-sql: true      # Affiche les requêtes SQL dans les logs
    properties:
      hibernate:
        format_sql: true  # Formate les requêtes SQL pour une meilleure lisibilité
        dialect: org.hibernate.dialect.MySQL8Dialect
        cors:
          allowed-origins: "http://localhost:4200"  # Correct YAML format for CORS
          allowed-methods: "GET,POST,PUT,PATCH,DELETE"
          allow-credentials: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: moumnihoussem5@gmail.com  # Adresse e-mail Gmail
    password: ylbu oumd zhkd whik       # Mot de passe d'application Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000    # Timeout de connexion en ms
          timeout: 5000              # Timeout de lecture en ms
          writetimeout: 5000         # Timeout d'écriture en ms
  servlet:
    multipart:
      max-file-size: 10MB  # Taille maximale d'un fichier uploadé
      max-request-size: 20MB  # Taille maximale de la requête
  config:
    import: optional:configserver:http://localhost:8888  # Configuration Spring Cloud Config
  task:
    scheduling:
      pool:
        size: 10  # Taille du pool de threads pour les tâches planifiées

# Configuration spécifique à l'application
app:
  frontend-url: http://localhost:4200  # URL de votre application Angular
  interview:
    default-time: "14:00"             # Heure par défaut pour les entretiens
    days-until-interview: 4           # Nombre de jours avant l'entretien après acceptation
    reminder-hours-before: 24         # Rappel 24h avant l'entretien
    final-reminder-hours-before: 1    # Rappel final 1h avant
    link-activation-hours-before: 24  # Activation du lien 24h avant

logging:
  level:
    org.hibernate.SQL: DEBUG  # Active les logs SQL
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Active les logs des paramètres SQL
    com.Megaminds.Recrutement: DEBUG  # Logs pour votre application

springdoc:
  api-docs:
    enabled: true  # Active la documentation Swagger
  swagger-ui:
    enabled: true  # Active l'interface Swagger UI
