package com.megaminds.finance.Service;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import com.megaminds.finance.Entity.FinancialReport;
import org.springframework.stereotype.Service;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;

@Service
public class PdfService {

    public ByteArrayInputStream generateReportPdf(FinancialReport report) {
        try {
            Document document = new Document(PageSize.A4);
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            PdfWriter.getInstance(document, out);
            document.open();

            // Fonts
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20, BaseColor.DARK_GRAY);
            Font labelFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
            Font valueFont = FontFactory.getFont(FontFactory.HELVETICA, 12);

            // Title
            Paragraph title = new Paragraph("📊 Financial Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            // Table
            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.setWidths(new int[]{1, 2});
            table.setSpacingBefore(10f);

            // Helper to add rows
            addRow(table, "Date du rapport :", report.getDate_rapport().toString(), labelFont, valueFont);
            addRow(table, "Revenu total :", report.getTotal_revenue() + " €", labelFont, valueFont);
            addRow(table, "Profit net :", report.getNet_profit() + " €", labelFont, valueFont);
            addRow(table, "Destinataire :", report.getEmail(), labelFont, valueFont);

            // Border styling
            table.getDefaultCell().setBorderColor(BaseColor.LIGHT_GRAY);
            document.add(table);

            // Footer
            Paragraph footer = new Paragraph("Generated by MegaMinds Finance System", valueFont);
            footer.setAlignment(Element.ALIGN_CENTER);
            footer.setSpacingBefore(40);
            footer.setFont(FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 10, BaseColor.GRAY));
            document.add(footer);

            document.close();
            return new ByteArrayInputStream(out.toByteArray());

        } catch (Exception e) {
            throw new RuntimeException("Erreur lors de la génération du PDF", e);
        }
    }

    private void addRow(PdfPTable table, String label, String value, Font labelFont, Font valueFont) {
        PdfPCell labelCell = new PdfPCell(new Phrase(label, labelFont));
        labelCell.setPadding(8);
        labelCell.setBackgroundColor(new BaseColor(245, 245, 245));
        labelCell.setBorderColor(BaseColor.LIGHT_GRAY);

        PdfPCell valueCell = new PdfPCell(new Phrase(value, valueFont));
        valueCell.setPadding(8);
        valueCell.setBorderColor(BaseColor.LIGHT_GRAY);

        table.addCell(labelCell);
        table.addCell(valueCell);
    }
}
